#!/usr/bin/env bash
# Install Nginx on a server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
# echo 'Hello World!' >  /var/www/html/index.nginx-debian.html

sudo service nginx restart
