#!/usr/bin/env bash
# Manages manage_my_process 

start() {
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop() {
	a=$(pgrep -f ./manage_my_process)
	kill -9 "$a"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

restart() {
	a=$(pgrep -f ./manage_my_process)
	kill -9 "$a"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

case "$1" in
	start) start ;;
	stop) stop ;;
	restart) restart ;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
