#!/usr/bin/env bash
# Configuring Apache Server in container

# Modify the index page
sudo bash -c 'echo "Hello Holberton" > /var/www/html/index.html'

# Start the Apache service
service apache2 start
