#!/usr/bin/env bash
# Running Nginx as user `nginx` (7 lines or less)
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx /usr/sbin/nginx
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
