#!/usr/bin/env bash
# Create an RSA key pair
# Name of the private key must be `school`
# Number of bits in the key is 4096
# The created key must be protected with the passphrase `betty`

ssh-keygen -b 4096 -t school -f rsa -N betty
